server:
  port: 8081
spring:
  application:
    name: station-app
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL JDBC driver
    url: jdbc:mysql://localhost:3307/train_information_db?useSSL=false&serverTimezone=UTC # Database URL
    username: root # MySQL username
    password: Javat2023 # MySQL password
  jpa:
    hibernate:
      ddl-auto: update #   Automatically update the schema
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # MySQL Dialect
    show-sql: true
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
  endpoint:
    health:
      show-details: always